# Generated by Django 4.0 on 2021-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_review_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
